module.exports = {
    path: {
        build: {
            html: '../build/assets/tpl',
            pageList: '../build/assets/',
            js: '../build/assets/js/',
            jsPages: '../build/assets/js/pages',
            cssPages: '../build/assets/style/pages',
            css: '../build/assets/style/',
            img: '../build/assets/img/',
            images: '../build/assets/images/',
            fonts: '../build/assets/fonts/',
            vendors: '../build/assets/vendors/',
            serve: '../build/assets/',
            serveIndex: 'index.html',
        },
        html: {
            html: '../html/assets/tpl/',
            pageList: '../html/assets/',
            js: '../html/assets/js/',
            jsPages: '../html/assets/js/pages',
            css: '../html/assets/style/',
            cssPages: '../html/assets/style/pages',
            img: '../html/assets/img/',
            images: '../html/assets/images/',
            fonts: '../html/assets/fonts/',
            vendors: '../html/assets/vendors/',
            serve: '../html/assets/',
            serveIndex: 'index.html',
        },
        src: {
            html: ['src/tpl/**/*.html'],
            htmlHtml: ['src/**/*.html'],
            // pug: 'src/tpl/**/*.pug',
            // pugHtml: 'src/**/*.pug',
            pageList: 'src/*.html',
            vendors: 'src/vendors/**/*',
            js: 'src/js/*.js',
            jsPages: 'src/js/pages/*.js',
            jsLibs: 'src/js/libs.js',
            style: 'src/style/*.scss',
            stylePages: 'src/style/pages/*.scss',
            img: ['src/img/**/*.*', '!src/img/sprite-icon/**/*.*'],
            images: 'src/images/**/*.*',
            spriteSass: 'src/style/utils/',
            spriteOrigin: 'src/img/sprite-icon/*.+(JPG|jpg|jpeg|png)',
            spriteImgPath: 'src/img/',
            spriteimgName: '../img/sprite/sprite.png',
            fonts: 'src/fonts/**/*.+(eot|woff2|woff|ttf|svg)',
        },
        watch: {
            html: 'src/**/*.html',
            pageList: 'src/*.html',
            vendors: 'src/vendors/**/*',
            // pug: 'src/**/*.pug',
            // pageList: 'src/*.pug',
            js: 'src/js/**/*.js',
            jsPages: 'src/js/pages/*.js',
            jsLibs: 'src/js/modules/**/*.js',
            style: 'src/style/**/*.+(scss|sass)',
            img: ['src/img/**/*.+(jpg|JPG|jpeg|png|svg|gif|ico)'],
            images: 'src/images/**/*.+(jpg|JPG|jpeg|png|svg|gif|ico)',
            fonts: 'src/fonts/**/*.+(eot|woff2|woff|ttf|svg)',
        },
        clean: '../build/assets',
        cleanHtml: '../html/assets',

    }
};